### ISSUE TITLE
Use the title of the file for its name when downloading it.

### ISSUE THREAD

**Issue by skounis** [skounis/europa-component-library#3]
Currently when we download a file the target name is always `file.{ext}` 

## Tasks
1. [x]  Create a branch
2. [x] Apply the existing `1.9.0` patch in the `blellow` theme
    - patches/@ecl/generic-component-file+1.9.0.patch
3. [x] Apply the patch for using actual file names
    - https://gitlab.dgcnect.eu/web-team/blellow-d8-theme/issues/432
4. [x] Create a new patch over the file in the repository, `v1.9.0`
